#!/usr/bin/env ruby

path = File.expand_path File.dirname(__FILE__)
system "sudo ln -s #{path}/tweetstormgenerator /usr/local/bin/tweetstormgenerator"
puts "Now you will be able to use /usr/local/bin/tweetstormgenerator or tweetstormgenerator from anywhere "
